<?php

namespace Justimmo\Api\Request;

use Justimmo\Api\Entity\Geo\City;

/**
 * Class CityRequest
 * @package Justimmo\Api\Request
 *
 * @method $this sortByCity($direction = BaseApiRequest::ASC)
 */
class CityRequest extends BaseApiRequest
{
    use RealtyFilterable;

    const SORTS = [
        'city',
    ];

    /**
     * Return the path prefix
     *
     * @return string
     */
    protected function getPathPrefix()
    {
        return '/cities';
    }

    /**
     * Returns class name for entities generated by this request
     *
     * @return string
     */
    public function getEntityClass()
    {
        return City::class;
    }
}
