<?php

namespace Justimmo\Api\Request;

interface RequestInterface
{
    /**
     * Returns the path to be called
     *
     * @return string
     */
    public function getPath();

    /**
     * Returns an array to be sent as query string
     *
     * @return array
     */
    public function getQuery();

    /**
     * Returns HTTP method
     *
     * @return string
     */
    public function getMethod();

    /**
     * Returns class name for entities generated by this request
     *
     * @return string
     */
    public function getEntityClass();
}
