name: CI

on: [ push ]

jobs:
    build-test-70:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 7.1
                version: 2.0.0
        -   uses: php-actions/phpunit@v3
            with:
                version: 6
                php_version: 7.0
    build-test-71:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 7.1
                version: 2.0.0
        -   uses: php-actions/phpunit@v3
            with:
                version: 6
                php_version: 7.1
    build-test-72:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 7.2
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 7.2
    build-test-73:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 7.3
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 7.3
    build-test-74:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 7.4
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 7.4
    build-test-80:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 8.0
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 8.0
    build-test-81:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 8.1
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 8.1
    build-test-82:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 8.2
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 8.2
    build-test-83:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 8.3
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 8.3
