name: CI

on: [ push ]

jobs:
    build-test-81:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 8.1
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 8.1
    build-test-82:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 8.2
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 8.2
    build-test-83:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: php-actions/composer@v6
            with:
                php_version: 8.3
        -   uses: php-actions/phpunit@v3
            with:
                version: 8
                php_version: 8.3
